name = "SimpleClifford"
uuid = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]
version = "0.1.0"

[deps]
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
